CARDS = {
    ("2", "♣"): "clubs_02.png",
    ("3", "♣"): "clubs_03.png",
    ("4", "♣"): "clubs_04.png",
    ("5", "♣"): "clubs_05.png",
    ("6", "♣"): "clubs_06.png",
    ("7", "♣"): "clubs_07.png",
    ("8", "♣"): "clubs_08.png",
    ("9", "♣"): "clubs_09.png",
    ("10", "♣"): "clubs_10.png",
    ("J", "♣"): "clubs_J.png",
    ("Q", "♣"): "clubs_Q.png",
    ("K", "♣"): "clubs_K.png",
    ("A", "♣"): "clubs_A.png",

    ("2", "♦"): "diamonds_02.png",
    ("3", "♦"): "diamonds_03.png",
    ("4", "♦"): "diamonds_04.png",
    ("5", "♦"): "diamonds_05.png",
    ("6", "♦"): "diamonds_06.png",
    ("7", "♦"): "diamonds_07.png",
    ("8", "♦"): "diamonds_08.png",
    ("9", "♦"): "diamonds_09.png",
    ("10", "♦"): "diamonds_10.png",
    ("J", "♦"): "diamonds_J.png",
    ("Q", "♦"): "diamonds_Q.png",
    ("K", "♦"): "diamonds_K.png",
    ("A", "♦"): "diamonds_A.png",

    ("2", "♠"): "spades_02.png",
    ("3", "♠"): "spades_03.png",
    ("4", "♠"): "spades_04.png",
    ("5", "♠"): "spades_05.png",
    ("6", "♠"): "spades_06.png",
    ("7", "♠"): "spades_07.png",
    ("8", "♠"): "spades_08.png",
    ("9", "♠"): "spades_09.png",
    ("10", "♠"): "spades_10.png",
    ("J", "♠"): "spades_J.png",
    ("Q", "♠"): "spades_Q.png",
    ("K", "♠"): "spades_K.png",
    ("A", "♠"): "spades_A.png",

    ("2", "♥"): "hearts_02.png",
    ("3", "♥"): "hearts_03.png",
    ("4", "♥"): "hearts_04.png",
    ("5", "♥"): "hearts_05.png",
    ("6", "♥"): "hearts_06.png",
    ("7", "♥"): "hearts_07.png",
    ("8", "♥"): "hearts_08.png",
    ("9", "♥"): "hearts_09.png",
    ("10", "♥"): "hearts_10.png",
    ("J", "♥"): "hearts_J.png",
    ("Q", "♥"): "hearts_Q.png",
    ("K", "♥"): "hearts_K.png",
    ("A", "♥"): "hearts_A.png",
}

PLAYER_ICONS = {
    "player1": "1.png",
    "player2": "2.png",
    "player3": "3.png",
    "player4": "4.png",
}
