IMAGE_DIRECTORY = 'images/cards/'
PLAYER_ICONS_DIR = 'images/players/'
SOUND_DIRECTORY = 'sound/'

SCREEN_WIDTH = 1380
SCREEN_HEIGHT = 720

FPS = 60

SCREEN_MARGIN_X = 100
SCREEN_MARGIN_Y = 100

CARD_WIDTH = 64
CARD_HEIGHT = 64
CARD_SPACING = -10

NUM_PLAYERS = 4
